export const HEADER_NAV_ITEMS_MAX = 8
export const HEADER_DROPDOWN_DESCRIPTION_LINKS_MAX = 3
export const HEADER_DROPDOWN_ITEMS_MIN = 1
export const HEADER_DROPDOWN_ITEMS_MAX = 12
export const HEADER_FEATURED_NAV_LINKS_MAX = 4
export const HEADER_LIST_NAV_LINKS_MIN = 1
export const HEADER_LIST_NAV_LINKS_MAX = 8
